# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: esmd-serverless-lambdas

frameworkVersion: '3'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x

  iam:
    role: arn:aws:iam::030556409702:role/esmd_serverless_role

  deploymentBucket:
    name: esmd-aws-generic-bucket-siva # Overwrite the default deployment bucket
    #serverSideEncryption: AES256 # when using server-side encryption

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: lambdas/hello-world/index.helloWorld
    package:
      individually: true
    # package:
    #   include:
    #     - lambdas/hello-world/
    #   exclude:
    #     - lambdas/ob-file-initial-validations
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true

  esMDOutboundFileInitialValidations:
    handler: lambdas/esmd-outbound-file-initial-validations/index.handler
    runtime: nodejs12.x
    vpc:
      securityGroupIds:
        - sg-03151b54033e5158d
      subnetIds:
        - subnet-0c3a4f372e820d41c
        - subnet-02e013088b137a8ce

    memorySize: 256 # optional, in MB, default is 1024
    timeout: 30 # 
    package:
      individually: true
    events: 
      - sqs: arn:aws:sqs:us-east-1:030556409702:esmd-process-outbound-files 
    environment:
      ENVIRONMENT_NAME: dev
      SM_PGS_DB_AUTH: dev_esmd_db_secret
      pgs_idle_time_out: 90000
      pgs_conn_time_out: 5000
      max_allowed_file_size: 1073741824  # 1 GB
      ref_sql_to_get_new_guid: select esmd_data.generate_global_unique_id(nextval('esmd_data.seq_guid_id'))
      ref_sql_to_get_guid: select glbl_uniq_id from esmd_data.submsn_trans where pkg_name_title_txt=$1 and pgm_line_of_busns_id=$2
      ref_sql_for_file_dup_chk: select count(*) as trans_count from esmd_data.submsn_trans where pkg_name_title_txt=$1 and pgm_line_of_busns_id=$2
      process_dcf_queue: https://sqs.us-east-1.amazonaws.com/030556409702/esmd-process-dcf-queue.fifo
      process_icdt_queue: https://sqs.us-east-1.amazonaws.com/030556409702/esmd-process-icdt-queue.fifo
      process_emdr_prepay_queue: https://sqs.us-east-1.amazonaws.com/030556409702/esmd-process-emdr-prepay-queue.fifo
      process_emdr_postpay_queue: https://sqs.us-east-1.amazonaws.com/030556409702/esmd-process-emdr-postpay-queue.fifo
      audit_queue_url: https://sqs.us-east-1.amazonaws.com/030556409702/esmd_audit_queue.fifo
      success_audit_event: transaction_id^transaction_id,request_type^lambda,worker_name^esMDOutboundFileValidations,date_timestamp^date_timestamp,hostname^null,activity_name^null,audit_message_id^SS_FLATFILE_REC_GEN_SUCCESS,audit_message^ZIP FILE HAS BEEN EXTRACTED SUCCESSFULLY AND SENT THE MESSAGE TO PROCESS QUEUE FOR FURTHER PROCESS
      failure_audit_event: transaction_id^transaction_id,request_type^lambda,worker_name^esMDOutboundFileValidations,date_timestamp^date_timestamp,hostname^null,activity_name^null,audit_message_id^ERROR_EXCEPTION_INTERNAL_SERVER_ERROR,audit_message^ERROR EXCEPTION:INTERNAL SERVER ERROR
      dcf_rec_insert_tbl_name: esmd_data.submsn_trans
      dcf_rec_insert_cols: submsn_trans_id^nextval('esmd_data.seq_submsn_trans_id')~formula,glbl_uniq_id^glbl_uniq_id,pkg_name_title_txt^pkg_name_title_txt,sendr_id ^88,sendr_type_id^6,pgm_line_of_busns_id^pgm_line_of_busns_id,submsn_type_id^1
      dup_pcg_notification: DUPLICATE_CSV_FILE_FROM_PCG
      notification_queue_url: https://sqs.us-east-1.amazonaws.com/030556409702/esmd_email_queue.fifo
      MAX_ATTEMPTS: 1

  
  # outboundFileInitialValidationsLambdaLogGroup:
  #   type: AWS::Logs::LogGroup
  #   # DeletionPolicy: 90 # ${LOG_RETENTION_POLICY}
  #   Properties:
  #     # LogGroupName: !Sub /aws/lambda/sc-in-frs-s3-to-dynamodb-service-tci-${deployEnv}-${version}
  #     LogGroupName: !Sub /aws/lambda/ob-file-initial-validations-dev
  #     # RetentionInDays: !Ref 90